finished first 3 files - Gabriel Enciso
gabrielenciso/ds-py-0122-code-solutions pull request #10
Opened 2022-01-15 19:50 UTC by gabrielenciso

dict_columns:

<img width="1512" alt="Screen Shot 2022-01-14 at 1 30 47 PM" src="https://user-images.githubusercontent.com/91447324/149635778-ee21f66e-412c-40f6-b573-5e5b7e41ed24.png">

dict_labels:

<img width="1207" alt="Screen Shot 2022-01-15 at 11 48 59 AM" src="https://user-images.githubusercontent.com/91447324/149635803-a6dbbc05-36c5-492b-8778-095f2b48b5bc.png">

list_dicts:

<img width="1208" alt="Screen Shot 2022-01-15 at 11 49 49 AM" src="https://user-images.githubusercontent.com/91447324/149635818-4738b4c2-ad5c-4a4b-8753-da174e46075b.png">

2022-01-15 19:55 UTC, TimelikeClosure commented on ds-prep-python-data-series/list_dicts.py
> +print(check_year(unemployment_rates, 2000, 2010))
@gabrielenciso  It'd be easier to use these results for other code logic if the `check_year` function returned a boolean(s) instead of descriptive string(s).

2022-01-15 21:03 UTC, TimelikeClosure requested changes
@gabrielenciso Looks pretty good so far. I did leave a couple notes, and please let me know when you're done with `list_tuples.py`.

2022-01-15 22:05 UTC, gabrielenciso commented
list_tuples:

<img width="1146" alt="Screen Shot 2022-01-15 at 2 05 08 PM" src="https://user-images.githubusercontent.com/91447324/149639130-d7808d98-bf52-4912-9682-d49f1aaea04d.png">

I made the same return values for the other #3's

2022-01-17 18:52 UTC, TimelikeClosure requested changes

2022-01-17 18:52 UTC, TimelikeClosure commented on ds-prep-python-data-series/list_tuples.py
> +print(last_appearing_series_point(unemployment_rates))
This should return a dictionary, not a tuple:

---

![image](https://user-images.githubusercontent.com/16143771/149823696-3cd3afdd-5b63-4a3d-a455-c13397bb935b.png)
****

2022-01-23 03:46 UTC, TimelikeClosure approved these changes

2022-04-26 21:48 UTC, merged